services:
    _defaults:
        public: true

    Aligent\InvoiceBundle\Controller\Frontend\FrontendInvoiceController:
        calls:
            - ['setContainer', ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }
